### PR TITLE
Adding Read ROI option, Change Read FMR function to allow latest FMR version

### PR DESCRIPTION
**Pull request by ju-ec**
Based on the voi.py file, I added the option to read the latest BV roi files (version 6)

### CODE REVIEW

**Comment by ofgulban** [comment]
Looks good, thanks @ju-ec :)

**Comment by ofgulban** [comment]
Looking at df47dbb94cc6d2f7f2fb91cd5f85928d8d98815d @ju-ec , are you sure that `ResolutionY` is `NrOfRows` and `ResolutionX` is `NrOfColumns`?

Do you have some new fmr data that is created in the latest version of Brainvoyager? If so can you run https://github.com/ofgulban/bvbabel/blob/main/examples/read_fmr_export_nifti.py on them to see if the conversion looks right? You can also send me the data.

I have encountered a case that makes me suspect that  actually `ResolutionX` is `NrOfRows` and `Resolution` is `ResolutionY`.

**Comment by ju-ec** [comment]
No, I am not 100% sure. I extracted that information from the New Document Wizard and the resulting FMR:

ResolutionFMR

When I run https://github.com/ofgulban/bvbabel/blob/main/examples/read_fmr_export_nifti.py on the created FMR, the resulting NIfTI is incorrect.

I will send you an example DCM.

**Comment by ju-ec** [comment]
Also when checking the final FMR: Resolution X represents the Nr of Columns and Resolution Y Nr of Rows.

**Comment by ju-ec** [comment]
I checked again and I think the problem is the communication between the fmr.py and the stc.py. 

In the parameter description of stc.py it states that:
_res_x: integer
        Number of voxels along each row in each slice. Referred to as
        "ResolutionX" within the FMR text file.
res_y: integer
        Number of voxels along each column in each slice. Referred to as
        "ResolutionY" within the FMR text file._
        
However, I believe it is the other way around: res_x should represent ResolutionY/NrOfRows, as you describe correctly it represents the number of voxels along each row, hence the number of columns.

**Pull request merged**
